<a href="https://colab.research.google.com/github/akso1234/DL/blob/main/inclass/03_DL_conj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### KNN(K-Nearest Neighbors)

import library & read csv data

In [57]:
# library & data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
# from sklearn.datasets import load_iris
# iris = load_iris()

# column of dataset
# names = ['Sepal-length', 'Sepal-width', 'Petal-length', 'Petal-width', 'Species']
# dataset = pd.read_csv('/content/dmu_data/Iris.csv')

# 2주차 데이터셋에서 id 열을 삭제한 데이터셋으로 작업하였습니다.
dataset = pd.read_csv('../content/sample_data/Data_all/Iris.csv')

search of data

In [58]:
dataset
# print(dataset)

# dataset.info()
# dataset.describe()

# dataset.head(5)
# dataset.tail()

# dataset.columns
# dataset.shape
# dataset.dtypes

# dataset.isnull().sum()

sepal-length  sepal-width  petal-length  petal-width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [59]:
# training과 test dataset 분리
X = dataset.iloc[0:, :-1].values # 모든 행은 사용하지만 열(칼럼)은 뒤에서 하나를 뺀 값을 가져와서 X에 저장
y = dataset.iloc[:, 4].values # 모든 행은 사용하지만, 열은 앞에서 다섯 번째 값만 가져와서 y에 저장

# X.shape
X
# y.shape
# y

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

training dataset : 90% / test dataset : 10%

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10) #test_dataset 10% 사용

X_train
# X_train.shape
# X_test.shape
# y_train.shape
# y_test.shape

array([[7.7, 3. , 6.1, 2.3],
       [6.1, 2.6, 5.6, 1.4],
       [5.7, 2.6, 3.5, 1. ],
       [7.9, 3.8, 6.4, 2. ],
       [6.3, 2.5, 4.9, 1.5],
       [6. , 2.2, 5. , 1.5],
       [5.9, 3. , 4.2, 1.5],
       [4.3, 3. , 1.1, 0.1],
       [6. , 3.4, 4.5, 1.6],
       [6. , 2.2, 4. , 1. ],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6.7, 3.3, 5.7, 2.1],
       [6.7, 3.3, 5.7, 2.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.4, 3.9, 1.7, 0.4],
       [6.5, 2.8, 4.6, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [5.1, 3.8, 1.5, 0.3],
       [5. , 3.5, 1.6, 0.6],
       [4.8, 3.4, 1.6, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6. , 3. , 4.8, 1.8],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 3.1, 4.7, 1.5],
       [6.9, 3.1, 5.4, 2.1],
       [4.4, 2.9, 1.4, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3.2, 1.2, 0.2],
       [6.5, 3

In [61]:
# Data Standardization(표준화) : Feature의 범위가 다른 경우에만 사용
from sklearn.preprocessing import StandardScaler
s = StandardScaler() # 특성 스케일링(scaling), 평균이 0, 표준편차가 1이 되도록 변환
s.fit(X_train) # 교과서를 변경한 부분

X_train = s.transform(X_train) # 훈련 데이터를 스케일링 처리
X_test = s.transform(X_test) # 테스트 데이터를 스케일링 처리

# X_train
X_test

array([[-0.07642727, -0.81546041,  0.18044748, -0.27280894],
       [ 0.52343791, -0.35771756,  1.02825755,  0.77199125],
       [-1.03621154, -1.73094611, -0.2717179 , -0.27280894],
       [-0.1964003 , -0.58658899,  0.18044748,  0.11899113],
       [ 1.48322218, -0.12884614,  1.19781957,  1.16379132],
       [-1.03621154,  1.01551099, -1.40213133, -1.1870091 ],
       [ 0.40346487, -0.58658899,  0.57609218,  0.77199125],
       [-0.43634637, -1.04433184,  0.35000949, -0.01160889],
       [ 0.28349184, -0.12884614,  0.46305084,  0.24959116],
       [-0.31637333, -0.12884614,  0.40653016,  0.38019118],
       [-0.91623851,  1.70212527, -1.0630073 , -1.05640908],
       [ 1.24327611,  0.10002529,  0.74565419,  1.42499136],
       [-1.51610368,  1.24438242, -1.57169334, -1.31760912],
       [-1.27615761, -0.12884614, -1.34561066, -1.44820914],
       [-0.79626547,  0.78663957, -1.34561066, -1.31760912]])

In [62]:
# create model (KNN)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10) # K의값 : 3, 5, 7, 9
# y_train = y_train.astype(int) # fix type arror
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=10)

In [63]:
# model accuracy
from sklearn import metrics
y_pred = knn.predict(X_test)
# y_test = y_test.astype(int)
print("Accuracy: {}".format(metrics.accuracy_score(y_test, y_pred)))

Accuracy: 1.0


In [64]:
#####################################################################
k = 10
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 1):
  classifier =  KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
  y_pred = classifier.predict(X_test)
  acc = metrics.accuracy_score(y_test, y_pred)
  acc_array[k-1] = acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("Accuracy is ", metrics.accuracy_score(y_test, y_pred), "for K-value", k)

Accuracy is  1.0 for K-value 0
